repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/omnilib/ufmt
    rev: v1.3.2
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 22.6.0
          - usort == 1.0.4

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.191
    hooks:
      - id: ruff
        exclude: (runhouse/grpc_handler/unary_pb2.py|runhouse/grpc_handler/unary_pb2_grpc.py)
        args: [--line-length=120, '--ignore=E402,E721,E722,E731,F821', '--per-file-ignores=__init__.py:F401']
