name: cluster-tests

on: workflow_dispatch

jobs:
  cluster-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure aws
        run: |
          aws configure set aws_access_key_id ${{ secrets.DEV_AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.DEV_AWS_SECRET_KEY }}
          aws configure set default.region us-east-1

      - name: Install & check skypilot configuration
        run: |
          python -m pip install --upgrade pip
          pip install skypilot
          sky check
          sky status

      - name: Install python packages & dependencies
        run: |
          pip install runhouse[aws]
          pip install -r tests/requirements.txt

      - name: Run all cluster unit tests tests
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: pytest -v tests/test_resources/test_cluster.py --level unit

      - name: Teardown all test clusters
        run: |
          sky status
          sky down --all -y
          sky status
