name: Generate docs for runhouse-docs
# https://cpina.github.io/push-to-another-repository-docs/index.html

on:
  push:
    branches:
      - '*'

env:
  RH_LOG_LEVEL: "INFO"

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install
        run: python -m pip install --upgrade pip && pip install -e .

      - name: Install docs requirements
        run: pip install -r docs/requirements.txt

      - name: Build docs
        run: cd docs && make json

      - name: Get current branch name
        run: echo "CURRENT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set target branch name
        run: echo "BRANCH_NAME=${CURRENT_BRANCH}" >> $GITHUB_ENV

      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'docs/_build/json/'
          destination-github-username: 'run-house'
          destination-repository-name: 'runhouse-docs'
          target-branch: ${{ env.BRANCH_NAME }}
          create-target-branch-if-needed: true
