name: Tests with level "local" on Den Dev

on:
  workflow_dispatch:

env:
  API_SERVER_URL: https://api-dev.run.house

jobs:
  # TODO: THESE ARE ONLY SEPARATE JOBS BECAUSE THERE ARE
  # DEVELOPMENT INCONSISTENCIES WHEN RUNNING ALL THE LOCAL
  # TESTS TOGETHER.
  # server-tests-logged-out-level-local:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3

  #     - name: Setup Runhouse
  #       uses: ./.github/workflows/setup_runhouse

  #     - name: pytest -v --level local tests/test_servers/
  #       env:
  #         KITCHEN_TESTER_DEV_TOKEN: ${{ secrets.KITCHEN_TESTER_DEV_TOKEN }}
  #         KITCHEN_TESTER_USERNAME: ${{ secrets.KITCHEN_TESTER_USERNAME }}
  #       run: pytest -v --level local tests/test_servers/

  server-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.DEN_TESTER_USERNAME }}
          token: ${{ secrets.DEN_TESTER_DEV_TOKEN }}
          api_server_url: ${{ env.API_SERVER_URL }}

      - name: Set Environment Variables for Dev
        run: |
          echo "KITCHEN_TESTER_TOKEN=${{ secrets.KITCHEN_TESTER_DEV_TOKEN }}" >> $GITHUB_ENV
          echo "ORG_MEMBER_TOKEN=${{ secrets.ORG_MEMBER_DEV_TOKEN }}" >> $GITHUB_ENV

      - name: pytest -v --level local tests/test_servers/
        env:
          KITCHEN_TESTER_TOKEN: ${{ env.KITCHEN_TESTER_TOKEN }}
          KITCHEN_TESTER_USERNAME: ${{ secrets.KITCHEN_TESTER_USERNAME }}
        run: pytest -v --level local tests/test_servers/ --api-server-url $API_SERVER_URL
        timeout-minutes: 60

  # most-tests-logged-out-level-local:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3

  #     - name: Setup Runhouse
  #       uses: ./.github/workflows/setup_runhouse

  #     - name: pytest -v --level local -k "not servertest and not secrettest"
  #       env:
  #         KITCHEN_TESTER_DEV_TOKEN: ${{ secrets.KITCHEN_TESTER_DEV_TOKEN }}
  #         KITCHEN_TESTER_USERNAME: ${{ secrets.KITCHEN_TESTER_USERNAME }}
  #       run: pytest -v --level local -k "not servertest and not secrettest"

  most-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.DEN_TESTER_USERNAME }}
          token: ${{ secrets.DEN_TESTER_DEV_TOKEN }}
          api_server_url: ${{ env.API_SERVER_URL }}

      - name: Set Environment Variables for Dev
        run: |
          echo "KITCHEN_TESTER_TOKEN=${{ secrets.KITCHEN_TESTER_DEV_TOKEN }}" >> $GITHUB_ENV
          echo "ORG_MEMBER_TOKEN=${{ secrets.ORG_MEMBER_DEV_TOKEN }}" >> $GITHUB_ENV

      - name: pytest -v --level local -k "not servertest and not secrettest and not moduletest and not functiontest and not envtest"
        env:
          KITCHEN_TESTER_TOKEN: ${{ env.KITCHEN_TESTER_TOKEN }}
          KITCHEN_TESTER_USERNAME: ${{ secrets.KITCHEN_TESTER_USERNAME }}
          ORG_MEMBER_TOKEN: ${{ env.ORG_MEMBER_TOKEN }}
          ORG_MEMBER_USERNAME: ${{ secrets.ORG_MEMBER_USERNAME }}
        run: pytest -v --level local -k "not servertest and not secrettest and not moduletest and not functiontest and not envtest" --api-server-url $API_SERVER_URL
        timeout-minutes: 60

  # secret-tests-logged-out-level-local:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3

  #     - name: Setup Runhouse
  #       uses: ./.github/workflows/setup_runhouse

  #     - name: pytest -v --level local -k "secrettest"
  #       env:
  #         KITCHEN_TESTER_DEV_TOKEN: ${{ secrets.KITCHEN_TESTER_DEV_TOKEN }}
  #         KITCHEN_TESTER_USERNAME: ${{ secrets.KITCHEN_TESTER_USERNAME }}
  #       run: pytest -v --level local -k "secrettest"

  secret-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.DEN_TESTER_USERNAME }}
          token: ${{ secrets.DEN_TESTER_DEV_TOKEN }}
          api_server_url: ${{ env.API_SERVER_URL }}

      - name: Set Environment Variables for Dev
        run: |
          echo "KITCHEN_TESTER_TOKEN=${{ secrets.KITCHEN_TESTER_DEV_TOKEN }}" >> $GITHUB_ENV
          echo "ORG_MEMBER_TOKEN=${{ secrets.ORG_MEMBER_DEV_TOKEN }}" >> $GITHUB_ENV

      - name: pytest -v --level local -k "secrettest"
        env:
          KITCHEN_TESTER_TOKEN: ${{ env.KITCHEN_TESTER_TOKEN }}
          KITCHEN_TESTER_USERNAME: ${{ secrets.KITCHEN_TESTER_USERNAME }}
          ORG_MEMBER_TOKEN: ${{ env.ORG_MEMBER_TOKEN }}
          ORG_MEMBER_USERNAME: ${{ secrets.ORG_MEMBER_USERNAME }}
        run: pytest -v --level local -k "secrettest" --api-server-url $API_SERVER_URL
        timeout-minutes: 60

  module-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.DEN_TESTER_USERNAME }}
          token: ${{ secrets.DEN_TESTER_DEV_TOKEN }}
          api_server_url: ${{ env.API_SERVER_URL }}

      - name: Set Environment Variables for Dev
        run: |
          echo "KITCHEN_TESTER_TOKEN=${{ secrets.KITCHEN_TESTER_DEV_TOKEN }}" >> $GITHUB_ENV
          echo "ORG_MEMBER_TOKEN=${{ secrets.ORG_MEMBER_DEV_TOKEN }}" >> $GITHUB_ENV

      - name: pytest -v --level local -k "moduletest"
        env:
          KITCHEN_TESTER_TOKEN: ${{ env.KITCHEN_TESTER_TOKEN }}
          KITCHEN_TESTER_USERNAME: ${{ secrets.KITCHEN_TESTER_USERNAME }}
          ORG_MEMBER_TOKEN: ${{ env.ORG_MEMBER_TOKEN }}
          ORG_MEMBER_USERNAME: ${{ secrets.ORG_MEMBER_USERNAME }}
        run: pytest -v --level local -k "moduletest" --api-server-url $API_SERVER_URL
        timeout-minutes: 60

  function-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.DEN_TESTER_USERNAME }}
          token: ${{ secrets.DEN_TESTER_DEV_TOKEN }}
          api_server_url: ${{ env.API_SERVER_URL }}

      - name: Set Environment Variables for Dev
        run: |
          echo "KITCHEN_TESTER_TOKEN=${{ secrets.KITCHEN_TESTER_DEV_TOKEN }}" >> $GITHUB_ENV
          echo "ORG_MEMBER_TOKEN=${{ secrets.ORG_MEMBER_DEV_TOKEN }}" >> $GITHUB_ENV

      - name: pytest -v --level local -k "functiontest"
        env:
          KITCHEN_TESTER_TOKEN: ${{ env.KITCHEN_TESTER_TOKEN }}
          KITCHEN_TESTER_USERNAME: ${{ secrets.KITCHEN_TESTER_USERNAME }}
          ORG_MEMBER_TOKEN: ${{ env.ORG_MEMBER_TOKEN }}
          ORG_MEMBER_USERNAME: ${{ secrets.ORG_MEMBER_USERNAME }}
        run: pytest -v --level local -k "functiontest" --api-server-url $API_SERVER_URL
        timeout-minutes: 60

  env-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.DEN_TESTER_USERNAME }}
          token: ${{ secrets.DEN_TESTER_DEV_TOKEN }}
          api_server_url: ${{ env.API_SERVER_URL }}

      - name: Set Environment Variables for Dev
        run: |
          echo "KITCHEN_TESTER_TOKEN=${{ secrets.KITCHEN_TESTER_DEV_TOKEN }}" >> $GITHUB_ENV
          echo "ORG_MEMBER_TOKEN=${{ secrets.ORG_MEMBER_DEV_TOKEN }}" >> $GITHUB_ENV

      - name: pytest -v --level local -k "envtest"
        env:
          KITCHEN_TESTER_TOKEN: ${{ env.KITCHEN_TESTER_TOKEN }}
          KITCHEN_TESTER_USERNAME: ${{ secrets.KITCHEN_TESTER_USERNAME }}
          ORG_MEMBER_TOKEN: ${{ env.ORG_MEMBER_TOKEN }}
          ORG_MEMBER_USERNAME: ${{ secrets.ORG_MEMBER_USERNAME }}
        run: pytest -v --level local -k "envtest" --api-server-url $API_SERVER_URL
        timeout-minutes: 60
