name: Tests with level "local"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # TODO: THESE ARE ONLY SEPARATE JOBS BECAUSE THERE ARE
  # DEVELOPMENT INCONSISTENCIES WHEN RUNNING ALL THE LOCAL
  # TESTS TOGETHER.
  # server-tests-logged-out-level-local:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3

  #     - name: Setup Runhouse
  #       uses: ./.github/workflows/setup_runhouse

  #     - name: pytest -v --level local tests/test_servers/
  #       env:
  #         TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
  #         TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
  #       run: pytest -v --level local tests/test_servers/

  server-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.CI_ACCOUNT_USERNAME }}
          token: ${{ secrets.CI_ACCOUNT_TOKEN }}

      - name: pytest -v --level local tests/test_servers/
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        run: pytest -v --level local tests/test_servers/
        timeout-minutes: 60

  # most-tests-logged-out-level-local:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3

  #     - name: Setup Runhouse
  #       uses: ./.github/workflows/setup_runhouse

  #     - name: pytest -v --level local -k "not servertest and not secrettest"
  #       env:
  #         TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
  #         TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
  #       run: pytest -v --level local -k "not servertest and not secrettest"

  most-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.CI_ACCOUNT_USERNAME }}
          token: ${{ secrets.CI_ACCOUNT_TOKEN }}

      - name: pytest -v --level local -k "not servertest and not secrettest and not moduletest and not functiontest and not envtest"
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        run: pytest -v --level local -k "not servertest and not secrettest and not moduletest and not functiontest and not envtest"
        timeout-minutes: 60

  # secret-tests-logged-out-level-local:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3

  #     - name: Setup Runhouse
  #       uses: ./.github/workflows/setup_runhouse

  #     - name: pytest -v --level local -k "secrettest"
  #       env:
  #         TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
  #         TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
  #       run: pytest -v --level local -k "secrettest"

  secret-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.CI_ACCOUNT_USERNAME }}
          token: ${{ secrets.CI_ACCOUNT_TOKEN }}

      - name: pytest -v --level local -k "secrettest"
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        run: pytest -v --level local -k "secrettest"
        timeout-minutes: 60

  module-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.CI_ACCOUNT_USERNAME }}
          token: ${{ secrets.CI_ACCOUNT_TOKEN }}

      - name: pytest -v --level local -k "moduletest"
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        run: pytest -v --level local -k "moduletest"
        timeout-minutes: 60

  function-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.CI_ACCOUNT_USERNAME }}
          token: ${{ secrets.CI_ACCOUNT_TOKEN }}

      - name: pytest -v --level local -k "functiontest"
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        run: pytest -v --level local -k "functiontest"
        timeout-minutes: 60

  env-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.CI_ACCOUNT_USERNAME }}
          token: ${{ secrets.CI_ACCOUNT_TOKEN }}

      - name: pytest -v --level local -k "envtest"
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        run: pytest -v --level local -k "envtest"
        timeout-minutes: 60
