name: test-login-flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  login-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages & dependencies
        run: |
          python -m pip install --upgrade pip
          pip install runhouse pytest fastapi ray[serve]

      - name: run login flow tests
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_AWS_ACCESS_KEY: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          TEST_AWS_SECRET_KEY: ${{ secrets.TEST_AWS_SECRET_KEY }}
          TEST_SKY_PRIVATE_KEY: ${{ secrets.TEST_SKY_PRIVATE_KEY }}
          TEST_SKY_PUBLIC_KEY: ${{ secrets.TEST_SKY_PUBLIC_KEY }}
        run: pytest -v -k logintest -m logintest
