name: Tests with level "unit"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  all-tests-level-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: pytest -v --level unit
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        run: pytest -v --level unit
